services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  netapp:
    build: netApp
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
